version: '2'
.catalog:
  name: Harbor
  version: 1.1.1-rev0-singlehost
  description: |
    Enterprise Class Container Registry [by VMware]
  minimum_rancher_version: v0.59.0
  uuid: harbor-2
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: myregistry
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "harborhostlabel"
      label: "Harbor will be deployed on the host with this label (default: harbor-host=true)"
      description: |
        Harbor host label
      default: harbor-host=true
      required: true
      type: "string"
services:
  registry:
    scale: 1
    start_on_create: false
  adminserver:
    scale: 1
    start_on_create: false
  proxy:
    scale: 1
    start_on_create: false
  jobservice:
    scale: 1
    start_on_create: false
  ui:
    scale: 1
    start_on_create: false
  mysql:
    scale: 1
    start_on_create: false
  harbor-setupwrapper:
    scale: 1
    start_on_create: true
