.catalog:
  name: Elasticsearch
  version: v2
  minimum_rancher_version: v1.2.0-pre4-rc1
  description: |
    You know, for search
  questions:
  - variable: SCHEDULER_PORT
    description: Port to expose scheduler on.
    label: Scheduler Port
    required: true
    type: int
    default: 31100
  - variable: NODE_COUNT
    description: Number of Elasticsearch instances to run.
    label: Node Count
    required: true
    type: int
    default: 3
scheduler:
  scale: 1
  health_check:
    port: ${SCHEDULER_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
