# notemplating
.catalog:
  name: "OVH DNS"
  version: "v0.1.0"
  description: "Rancher External DNS service powered by OVH"
  minimum_rancher_version: v1.6.0-rc1
  questions:
    - variable: "OVH_ENDPOINT"
      label: "OVH Endpoint"
      description: "Enter your endpoint"
      type: "string"
      required: true
    - variable: "OVH_APPLICATION_KEY"
      label: "OVH Application Key"
      description: "Enter your application key"
      type: "string"
      required: true
    - variable: "OVH_APPLICATION_SECRET"
      label: "OVH Application Secret"
      description: "Enter your application secret"
      type: "string"
      required: true
    - variable: "OVH_CONSUMER_KEY"
      label: "OVH Consumer Key"
      description: "Enter your consumer key"
      type: "string"
      required: true
    - variable: "ROOT_DOMAIN"
      label: "Domain Name"
      description: "The domain name managed by OVH."
      type: "string"
      required: true
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the domain) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false

ovh:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
