.catalog:
  name: Sentry
  version: 8.5.0
  description: Sentry is a realtime event logging and aggregation platform

  questions:
    - variable: "sentry_secret_key"
      type: "password"
      required: true
      label: "SENTRY_SECRET_KEY"
      description: "A secret key used for cryptographic functions within Sentry. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_public_port"
      type: "int"
      required: false
      label: "Sentry public port"
      description: "Port that Sentry will listen on. Alternatively you could point a load balancer to the port 9000 of this container"

    - variable: "sentry_initial_user_email"
      type: "string"
      required: true
      label: "SENTRY_INITIAL_USER_EMAIL"
      description: "The initial superuser email"

    - variable: "sentry_initial_user_password"
      type: "password"
      required: true
      label: "SENTRY_INITIAL_USER_PASSWORD"
      description: "The initial superuser password. Please use a simple initial password and change it afterwards in the Sentry interface"

    - variable: "sentry_server_email"
      type: "string"
      required: false
      label: "SENTRY_SERVER_EMAIL"
      description: "The email address used for 'From:'. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_host"
      type: "string"
      required: false
      label: "SENTRY_EMAIL_HOST"
      description: "The smtp server address. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_user"
      type: "string"
      required: false
      label: "SENTRY_EMAIL_USER"
      description: "The username for the email account. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_password"
      type: "password"
      required: false
      label: "SENTRY_EMAIL_PASSWORD"
      description: "The password for the email account. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_port"
      type: "int"
      required: false
      label: "SENTRY_EMAIL_PORT"
      description: "Port of the smtp server. see https://hub.docker.com/_/sentry/ for more info"
