.catalog:
  name: Avi Vantange Platform Load Balancer
  version: "v2-Avi"
  description: "External LB service powered by Avi Vantage Platform"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: "AVI_USER"
      label: "Avi account username"
      description: "User name for your account on Avi Controller"
      type: "string"
      required: true
    - variable: "AVI_PASSWORD"
      label: "Avi user account password"
      description: "Password for your account on Avi Controller"
      type: "password"
      required: false
    - variable: "AVI_CONTROLLER_ADDR"
      label: "Avi Controller IP Address"
      description: "IP Address of the Avi Controller"
      type: "string"
      required: true
    - variable: "AVI_CONTROLLER_PORT"
      label: "Avi Controller Port (Optional)"
      description: "Port on which Avi Controller is listening for API requests"
      type: "string"
      required: false
    - variable: "AVI_CLOUD_NAME"
      label: "Avi Cloud Name (Optional)"
      description: "Name of Avi Cloud in which Virtual Services are created"
      required: false
      type: "string"
    - variable: "AVI_SSL_VERIFY"
      label: "Avi SSL Verify (Optional)"
      description: "SSL certificate validation while connecting to Avi Controller"
      required: false
      type: "boolean"
      default: false
    - variable: "AVI_DNS_SUBDOMAIN"
      label: "Avi VS subdomain"
      description: "Avi Virtual services are created with the subdomain config"
      type: "string"
      required: false
    - variable: "AVI_TENANT"
      label: "Avi tenant name"
      description: "Avi Virtual service created in tenant"
      type: "string"
      required: false
      default: admin

avi:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
