version: '2'

catalog:
  name: "gitlab-multi-runner"
  version: "9.4.2"
  description: "a Gitlab pipelines multi-runner, that will spawn privates runners in your infra."
  minimum_rancher_version: v1.5.0
  # maximum_rancher_version:
  # upgrade_from: # The previous versions that this template can be upgraded from
  questions:
    - variable: "GITLAB_URL"
      label: "Gitlab Url"
      description: "Url to your Gitlab CI endpoint"
      type: "string"
      default: "https://gitlab.com/ci"
      required: true

    - variable: "GITLAB_TOKEN"
      label: "Gitlab Token"
      description: "Token provided in you project settings"
      type: "string"
      default: "xxxxxxxxxxxxxxxxxxxx"
      required: true

    - variable: "GITLAB_TAGS"
      label: "Gitlab Tags"
      description: "Tags to apply"
      type: "string"
      default: "dev"
      required: false

    - variable: "host_label"
      label: "Host with Label to deploy gitlab-runner on"
      description: |
        Host label to use as gitlab-runner 'value' tag.
        Example: 'gitlab-runner=true'
      type: "string"
      default: ""
      required: false

services:
  gitlab-runner-config:
    start_on_create: true
  gitlab-runner:
    start_on_create: true
