.catalog:
  version: v1.1.1-rancher2
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
  - variable: MARATHON_HTTP_PORT
    description: Port to expose Marathon on.
    label: Marathon Port
    required: true
    type: int
    default: 8080
marathon:
  scale: 1
  health_check:
    port: ${MARATHON_HTTP_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
