version: '2'

services:

  elasticsearch:
    scale: 1
    start_on_create: true

  nginx:
    scale: 1
    start_on_create: true

  postgresql:
    scale: 1
    start_on_create: true

  zammad:
    scale: 1
    start_on_create: true

  zammad-scheduler:
    scale: 1
    start_on_create: true

  zammad-railsserver:
    scale: 1
    start_on_create: true

  zammad-websocket:
    scale: 1
    start_on_create: true
